Summary: live555 version 20160919-r0
Name: live555
Version: 20160919
Release: r0
License: LGPLv3
Group: devel
Packager: Poky <poky@yoctoproject.org>
URL: http://live.com/
BuildRequires: virtual/arm-poky-linux-gnueabi-compilerlibs
BuildRequires: virtual/libc
BuildRequires: virtual/arm-poky-linux-gnueabi-gcc

%description
LIVE555 Streaming Media libraries

%package -n live555-dbg
Summary: live555 version 20160919-r0 - Debugging files
Group: devel

%description -n live555-dbg
LIVE555 Streaming Media libraries  This package contains ELF symbols and
related sources for debugging purposes.

%package -n live555-staticdev
Summary: live555 version 20160919-r0 - Development files (Static Libraries)
Group: devel
Requires: live555-dev = 20160919-r0

%description -n live555-staticdev
LIVE555 Streaming Media libraries  This package contains static libraries
for software development.

%package -n live555-dev
Summary: live555 version 20160919-r0 - Development files
Group: devel
Requires: live555 = 20160919-r0

%description -n live555-dev
LIVE555 Streaming Media libraries  This package contains symbolic links,
header files, and related items necessary for software development.

%package -n live555-doc
Summary: live555 version 20160919-r0 - Documentation files
Group: doc

%description -n live555-doc
LIVE555 Streaming Media libraries  This package contains documentation.

%package -n live555-locale
Summary: live555 version 20160919-r0
Group: devel

%description -n live555-locale
LIVE555 Streaming Media libraries

%files -n live555-dbg
%defattr(-,-,-,-)

%files -n live555-staticdev
%defattr(-,-,-,-)
%dir "/usr"
%dir "/usr/lib"
"/usr/lib/libgroupsock.a"
"/usr/lib/libBasicUsageEnvironment.a"
"/usr/lib/libUsageEnvironment.a"
"/usr/lib/libliveMedia.a"

%files -n live555-dev
%defattr(-,-,-,-)
%dir "/usr"
%dir "/usr/include"
%dir "/usr/include/groupsock"
%dir "/usr/include/liveMedia"
%dir "/usr/include/BasicUsageEnvironment"
%dir "/usr/include/UsageEnvironment"
"/usr/include/MP3ADUTranscoder.hh"
"/usr/include/HashTable.hh"
"/usr/include/ADTSAudioFileServerMediaSubsession.hh"
"/usr/include/MPEG4VideoStreamDiscreteFramer.hh"
"/usr/include/WAVAudioFileSource.hh"
"/usr/include/RTPSink.hh"
"/usr/include/H264VideoRTPSink.hh"
"/usr/include/MPEG1or2VideoRTPSink.hh"
"/usr/include/BitVector.hh"
"/usr/include/RTPSource.hh"
"/usr/include/H261VideoRTPSource.hh"
"/usr/include/MPEG1or2VideoStreamDiscreteFramer.hh"
"/usr/include/GenericMediaServer.hh"
"/usr/include/AMRAudioRTPSink.hh"
"/usr/include/version.hh"
"/usr/include/RTSPServer.hh"
"/usr/include/MPEGVideoStreamParser.hh"
"/usr/include/AudioInputDevice.hh"
"/usr/include/MPEG2IndexFromTransportStream.hh"
"/usr/include/EBMLNumber.hh"
"/usr/include/MPEG4LATMAudioRTPSink.hh"
"/usr/include/WAVAudioFileServerMediaSubsession.hh"
"/usr/include/H263plusVideoFileServerMediaSubsession.hh"
"/usr/include/MPEG1or2DemuxedElementaryStream.hh"
"/usr/include/SimpleRTPSource.hh"
"/usr/include/H263plusVideoStreamFramer.hh"
"/usr/include/MP3StreamState.hh"
"/usr/include/rtcp_from_spec.h"
"/usr/include/MPEG2TransportStreamFromESSource.hh"
"/usr/include/OutputFile.hh"
"/usr/include/MP3AudioFileServerMediaSubsession.hh"
"/usr/include/MP3ADURTPSource.hh"
"/usr/include/FramedFileSource.hh"
"/usr/include/MP3AudioMatroskaFileServerMediaSubsession.hh"
"/usr/include/FileSink.hh"
"/usr/include/MediaSession.hh"
"/usr/include/OggFileParser.hh"
"/usr/include/UsageEnvironment_version.hh"
"/usr/include/MP3Transcoder.hh"
"/usr/include/QCELPAudioRTPSource.hh"
"/usr/include/MatroskaFileParser.hh"
"/usr/include/ourMD5.hh"
"/usr/include/MPEG1or2AudioStreamFramer.hh"
"/usr/include/GroupsockHelper.hh"
"/usr/include/MPEG4LATMAudioRTPSource.hh"
"/usr/include/MPEG4GenericRTPSink.hh"
"/usr/include/OggFile.hh"
"/usr/include/MP3Internals.hh"
"/usr/include/H265VideoStreamFramer.hh"
"/usr/include/WindowsAudioInputDevice_common.hh"
"/usr/include/H265VideoStreamDiscreteFramer.hh"
"/usr/include/OggDemuxedTrack.hh"
"/usr/include/MPEG2TransportStreamTrickModeFilter.hh"
"/usr/include/OggFileServerMediaSubsession.hh"
"/usr/include/MultiFramedRTPSource.hh"
"/usr/include/NetCommon.h"
"/usr/include/H264or5VideoRTPSink.hh"
"/usr/include/BasicUsageEnvironment0.hh"
"/usr/include/StreamReplicator.hh"
"/usr/include/DynamicRTSPServer.hh"
"/usr/include/MPEG1or2AudioRTPSink.hh"
"/usr/include/WindowsAudioInputDevice_mixer.hh"
"/usr/include/RTSPClient.hh"
"/usr/include/MPEG1or2VideoStreamFramer.hh"
"/usr/include/MPEG4VideoFileServerMediaSubsession.hh"
"/usr/include/MediaTranscodingTable.hh"
"/usr/include/MediaSource.hh"
"/usr/include/MPEG1or2FileServerDemux.hh"
"/usr/include/TheoraVideoRTPSource.hh"
"/usr/include/UsageEnvironment.hh"
"/usr/include/MediaSink.hh"
"/usr/include/Groupsock.hh"
"/usr/include/BasicUDPSource.hh"
"/usr/include/PassiveServerMediaSubsession.hh"
"/usr/include/H264VideoRTPSource.hh"
"/usr/include/OggFileSink.hh"
"/usr/include/MP3ADUdescriptor.hh"
"/usr/include/Locale.hh"
"/usr/include/MatroskaFileServerMediaSubsession.hh"
"/usr/include/AMRAudioFileSource.hh"
"/usr/include/DVVideoRTPSource.hh"
"/usr/include/SIPClient.hh"
"/usr/include/H263plusVideoStreamParser.hh"
"/usr/include/MPEG1or2AudioRTPSource.hh"
"/usr/include/BasicUsageEnvironment.hh"
"/usr/include/HandlerSet.hh"
"/usr/include/MPEG2TransportUDPServerMediaSubsession.hh"
"/usr/include/uLawAudioFilter.hh"
"/usr/include/ServerMediaSession.hh"
"/usr/include/H265VideoRTPSource.hh"
"/usr/include/playCommon.hh"
"/usr/include/H264or5VideoStreamDiscreteFramer.hh"
"/usr/include/MPEG1or2VideoRTPSource.hh"
"/usr/include/DVVideoStreamFramer.hh"
"/usr/include/MatroskaDemuxedTrack.hh"
"/usr/include/MPEG1or2Demux.hh"
"/usr/include/OnDemandServerMediaSubsession.hh"
"/usr/include/QuickTimeGenericRTPSource.hh"
"/usr/include/VP9VideoRTPSink.hh"
"/usr/include/H264or5VideoStreamFramer.hh"
"/usr/include/VideoRTPSink.hh"
"/usr/include/DelayQueue.hh"
"/usr/include/ByteStreamFileSource.hh"
"/usr/include/H265VideoFileSink.hh"
"/usr/include/AC3AudioStreamFramer.hh"
"/usr/include/BasicHashTable.hh"
"/usr/include/NetAddress.hh"
"/usr/include/T140TextRTPSink.hh"
"/usr/include/H264VideoStreamDiscreteFramer.hh"
"/usr/include/H264VideoStreamFramer.hh"
"/usr/include/liveMedia_version.hh"
"/usr/include/MPEG2TransportFileServerMediaSubsession.hh"
"/usr/include/GSMAudioRTPSink.hh"
"/usr/include/BasicUsageEnvironment_version.hh"
"/usr/include/JPEGVideoRTPSource.hh"
"/usr/include/MultiFramedRTPSink.hh"
"/usr/include/DeviceSource.hh"
"/usr/include/ByteStreamMemoryBufferSource.hh"
"/usr/include/H265VideoFileServerMediaSubsession.hh"
"/usr/include/H263plusVideoRTPSink.hh"
"/usr/include/RTCP.hh"
"/usr/include/TextRTPSink.hh"
"/usr/include/DigestAuthentication.hh"
"/usr/include/MatroskaFileServerDemux.hh"
"/usr/include/AMRAudioFileSink.hh"
"/usr/include/ADTSAudioFileSource.hh"
"/usr/include/H265VideoRTPSink.hh"
"/usr/include/RTPInterface.hh"
"/usr/include/MP3ADU.hh"
"/usr/include/liveMedia.hh"
"/usr/include/MP3ADUinterleaving.hh"
"/usr/include/MPEG4GenericRTPSource.hh"
"/usr/include/AMRAudioRTPSource.hh"
"/usr/include/JPEGVideoRTPSink.hh"
"/usr/include/TCPStreamSink.hh"
"/usr/include/JPEGVideoSource.hh"
"/usr/include/OggFileServerDemux.hh"
"/usr/include/BasicUDPSink.hh"
"/usr/include/ByteStreamMultiFileSource.hh"
"/usr/include/AC3AudioRTPSource.hh"
"/usr/include/AC3AudioFileServerMediaSubsession.hh"
"/usr/include/VP8VideoRTPSource.hh"
"/usr/include/H264VideoFileSink.hh"
"/usr/include/groupsock_version.hh"
"/usr/include/IOHandlers.hh"
"/usr/include/MPEG1or2VideoFileServerMediaSubsession.hh"
"/usr/include/TunnelEncaps.hh"
"/usr/include/strDup.hh"
"/usr/include/MP3ADURTPSink.hh"
"/usr/include/MP3InternalsHuffman.hh"
"/usr/include/MPEG2TransportStreamMultiplexor.hh"
"/usr/include/MPEG4ESVideoRTPSource.hh"
"/usr/include/AC3AudioRTPSink.hh"
"/usr/include/FramedFilter.hh"
"/usr/include/MPEG2TransportStreamFramer.hh"
"/usr/include/VorbisAudioRTPSink.hh"
"/usr/include/MPEG4VideoStreamFramer.hh"
"/usr/include/MPEG4ESVideoRTPSink.hh"
"/usr/include/VP9VideoRTPSource.hh"
"/usr/include/H263plusVideoRTPSource.hh"
"/usr/include/RTSPServerSupportingHTTPStreaming.hh"
"/usr/include/Boolean.hh"
"/usr/include/SimpleRTPSink.hh"
"/usr/include/H264or5VideoFileSink.hh"
"/usr/include/WindowsAudioInputDevice_noMixer.hh"
"/usr/include/VP8VideoRTPSink.hh"
"/usr/include/QuickTimeFileSink.hh"
"/usr/include/ProxyServerMediaSession.hh"
"/usr/include/FramedSource.hh"
"/usr/include/MPEG2TransportStreamIndexFile.hh"
"/usr/include/DVVideoRTPSink.hh"
"/usr/include/MPEGVideoStreamFramer.hh"
"/usr/include/MPEG2TransportStreamFromPESSource.hh"
"/usr/include/AMRAudioSource.hh"
"/usr/include/AMRAudioFileServerMediaSubsession.hh"
"/usr/include/StreamParser.hh"
"/usr/include/MatroskaFile.hh"
"/usr/include/RTSPRegisterSender.hh"
"/usr/include/AVIFileSink.hh"
"/usr/include/VorbisAudioRTPSource.hh"
"/usr/include/TheoraVideoRTPSink.hh"
"/usr/include/NetInterface.hh"
"/usr/include/Media.hh"
"/usr/include/RTSPCommon.hh"
"/usr/include/Base64.hh"
"/usr/include/MPEG1or2DemuxedServerMediaSubsession.hh"
"/usr/include/AudioRTPSink.hh"
"/usr/include/H264VideoFileServerMediaSubsession.hh"
"/usr/include/GroupEId.hh"
"/usr/include/DVVideoFileServerMediaSubsession.hh"
"/usr/include/MP3FileSource.hh"
"/usr/include/FileServerMediaSubsession.hh"
"/usr/include/InputFile.hh"
"/usr/include/groupsock/GroupsockHelper.hh"
"/usr/include/groupsock/NetCommon.h"
"/usr/include/groupsock/Groupsock.hh"
"/usr/include/groupsock/NetAddress.hh"
"/usr/include/groupsock/groupsock_version.hh"
"/usr/include/groupsock/IOHandlers.hh"
"/usr/include/groupsock/TunnelEncaps.hh"
"/usr/include/groupsock/NetInterface.hh"
"/usr/include/groupsock/GroupEId.hh"
"/usr/include/liveMedia/MP3ADUTranscoder.hh"
"/usr/include/liveMedia/ADTSAudioFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MPEG4VideoStreamDiscreteFramer.hh"
"/usr/include/liveMedia/WAVAudioFileSource.hh"
"/usr/include/liveMedia/RTPSink.hh"
"/usr/include/liveMedia/H264VideoRTPSink.hh"
"/usr/include/liveMedia/MPEG1or2VideoRTPSink.hh"
"/usr/include/liveMedia/BitVector.hh"
"/usr/include/liveMedia/RTPSource.hh"
"/usr/include/liveMedia/H261VideoRTPSource.hh"
"/usr/include/liveMedia/MPEG1or2VideoStreamDiscreteFramer.hh"
"/usr/include/liveMedia/GenericMediaServer.hh"
"/usr/include/liveMedia/AMRAudioRTPSink.hh"
"/usr/include/liveMedia/RTSPServer.hh"
"/usr/include/liveMedia/AudioInputDevice.hh"
"/usr/include/liveMedia/MPEG2IndexFromTransportStream.hh"
"/usr/include/liveMedia/MPEG4LATMAudioRTPSink.hh"
"/usr/include/liveMedia/WAVAudioFileServerMediaSubsession.hh"
"/usr/include/liveMedia/H263plusVideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MPEG1or2DemuxedElementaryStream.hh"
"/usr/include/liveMedia/SimpleRTPSource.hh"
"/usr/include/liveMedia/H263plusVideoStreamFramer.hh"
"/usr/include/liveMedia/MPEG2TransportStreamFromESSource.hh"
"/usr/include/liveMedia/OutputFile.hh"
"/usr/include/liveMedia/MP3AudioFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MP3ADURTPSource.hh"
"/usr/include/liveMedia/FramedFileSource.hh"
"/usr/include/liveMedia/FileSink.hh"
"/usr/include/liveMedia/MediaSession.hh"
"/usr/include/liveMedia/MP3Transcoder.hh"
"/usr/include/liveMedia/QCELPAudioRTPSource.hh"
"/usr/include/liveMedia/ourMD5.hh"
"/usr/include/liveMedia/MPEG1or2AudioStreamFramer.hh"
"/usr/include/liveMedia/MPEG4LATMAudioRTPSource.hh"
"/usr/include/liveMedia/MPEG4GenericRTPSink.hh"
"/usr/include/liveMedia/OggFile.hh"
"/usr/include/liveMedia/H265VideoStreamFramer.hh"
"/usr/include/liveMedia/H265VideoStreamDiscreteFramer.hh"
"/usr/include/liveMedia/MPEG2TransportStreamTrickModeFilter.hh"
"/usr/include/liveMedia/MultiFramedRTPSource.hh"
"/usr/include/liveMedia/H264or5VideoRTPSink.hh"
"/usr/include/liveMedia/StreamReplicator.hh"
"/usr/include/liveMedia/MPEG1or2AudioRTPSink.hh"
"/usr/include/liveMedia/RTSPClient.hh"
"/usr/include/liveMedia/MPEG1or2VideoStreamFramer.hh"
"/usr/include/liveMedia/MPEG4VideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MediaTranscodingTable.hh"
"/usr/include/liveMedia/MediaSource.hh"
"/usr/include/liveMedia/MPEG1or2FileServerDemux.hh"
"/usr/include/liveMedia/TheoraVideoRTPSource.hh"
"/usr/include/liveMedia/MediaSink.hh"
"/usr/include/liveMedia/BasicUDPSource.hh"
"/usr/include/liveMedia/PassiveServerMediaSubsession.hh"
"/usr/include/liveMedia/H264VideoRTPSource.hh"
"/usr/include/liveMedia/OggFileSink.hh"
"/usr/include/liveMedia/Locale.hh"
"/usr/include/liveMedia/AMRAudioFileSource.hh"
"/usr/include/liveMedia/DVVideoRTPSource.hh"
"/usr/include/liveMedia/SIPClient.hh"
"/usr/include/liveMedia/MPEG1or2AudioRTPSource.hh"
"/usr/include/liveMedia/MPEG2TransportUDPServerMediaSubsession.hh"
"/usr/include/liveMedia/uLawAudioFilter.hh"
"/usr/include/liveMedia/ServerMediaSession.hh"
"/usr/include/liveMedia/H265VideoRTPSource.hh"
"/usr/include/liveMedia/H264or5VideoStreamDiscreteFramer.hh"
"/usr/include/liveMedia/MPEG1or2VideoRTPSource.hh"
"/usr/include/liveMedia/DVVideoStreamFramer.hh"
"/usr/include/liveMedia/MPEG1or2Demux.hh"
"/usr/include/liveMedia/OnDemandServerMediaSubsession.hh"
"/usr/include/liveMedia/QuickTimeGenericRTPSource.hh"
"/usr/include/liveMedia/VP9VideoRTPSink.hh"
"/usr/include/liveMedia/H264or5VideoStreamFramer.hh"
"/usr/include/liveMedia/VideoRTPSink.hh"
"/usr/include/liveMedia/ByteStreamFileSource.hh"
"/usr/include/liveMedia/H265VideoFileSink.hh"
"/usr/include/liveMedia/AC3AudioStreamFramer.hh"
"/usr/include/liveMedia/T140TextRTPSink.hh"
"/usr/include/liveMedia/H264VideoStreamDiscreteFramer.hh"
"/usr/include/liveMedia/H264VideoStreamFramer.hh"
"/usr/include/liveMedia/liveMedia_version.hh"
"/usr/include/liveMedia/MPEG2TransportFileServerMediaSubsession.hh"
"/usr/include/liveMedia/GSMAudioRTPSink.hh"
"/usr/include/liveMedia/JPEGVideoRTPSource.hh"
"/usr/include/liveMedia/MultiFramedRTPSink.hh"
"/usr/include/liveMedia/DeviceSource.hh"
"/usr/include/liveMedia/ByteStreamMemoryBufferSource.hh"
"/usr/include/liveMedia/H265VideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/H263plusVideoRTPSink.hh"
"/usr/include/liveMedia/RTCP.hh"
"/usr/include/liveMedia/TextRTPSink.hh"
"/usr/include/liveMedia/DigestAuthentication.hh"
"/usr/include/liveMedia/MatroskaFileServerDemux.hh"
"/usr/include/liveMedia/AMRAudioFileSink.hh"
"/usr/include/liveMedia/ADTSAudioFileSource.hh"
"/usr/include/liveMedia/H265VideoRTPSink.hh"
"/usr/include/liveMedia/RTPInterface.hh"
"/usr/include/liveMedia/MP3ADU.hh"
"/usr/include/liveMedia/liveMedia.hh"
"/usr/include/liveMedia/MP3ADUinterleaving.hh"
"/usr/include/liveMedia/MPEG4GenericRTPSource.hh"
"/usr/include/liveMedia/AMRAudioRTPSource.hh"
"/usr/include/liveMedia/JPEGVideoRTPSink.hh"
"/usr/include/liveMedia/TCPStreamSink.hh"
"/usr/include/liveMedia/JPEGVideoSource.hh"
"/usr/include/liveMedia/OggFileServerDemux.hh"
"/usr/include/liveMedia/BasicUDPSink.hh"
"/usr/include/liveMedia/ByteStreamMultiFileSource.hh"
"/usr/include/liveMedia/AC3AudioRTPSource.hh"
"/usr/include/liveMedia/AC3AudioFileServerMediaSubsession.hh"
"/usr/include/liveMedia/VP8VideoRTPSource.hh"
"/usr/include/liveMedia/H264VideoFileSink.hh"
"/usr/include/liveMedia/MPEG1or2VideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MP3ADURTPSink.hh"
"/usr/include/liveMedia/MPEG2TransportStreamMultiplexor.hh"
"/usr/include/liveMedia/MPEG4ESVideoRTPSource.hh"
"/usr/include/liveMedia/AC3AudioRTPSink.hh"
"/usr/include/liveMedia/FramedFilter.hh"
"/usr/include/liveMedia/MPEG2TransportStreamFramer.hh"
"/usr/include/liveMedia/VorbisAudioRTPSink.hh"
"/usr/include/liveMedia/MPEG4VideoStreamFramer.hh"
"/usr/include/liveMedia/MPEG4ESVideoRTPSink.hh"
"/usr/include/liveMedia/VP9VideoRTPSource.hh"
"/usr/include/liveMedia/H263plusVideoRTPSource.hh"
"/usr/include/liveMedia/RTSPServerSupportingHTTPStreaming.hh"
"/usr/include/liveMedia/SimpleRTPSink.hh"
"/usr/include/liveMedia/H264or5VideoFileSink.hh"
"/usr/include/liveMedia/VP8VideoRTPSink.hh"
"/usr/include/liveMedia/QuickTimeFileSink.hh"
"/usr/include/liveMedia/ProxyServerMediaSession.hh"
"/usr/include/liveMedia/FramedSource.hh"
"/usr/include/liveMedia/MPEG2TransportStreamIndexFile.hh"
"/usr/include/liveMedia/DVVideoRTPSink.hh"
"/usr/include/liveMedia/MPEGVideoStreamFramer.hh"
"/usr/include/liveMedia/MPEG2TransportStreamFromPESSource.hh"
"/usr/include/liveMedia/AMRAudioSource.hh"
"/usr/include/liveMedia/AMRAudioFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MatroskaFile.hh"
"/usr/include/liveMedia/RTSPRegisterSender.hh"
"/usr/include/liveMedia/AVIFileSink.hh"
"/usr/include/liveMedia/VorbisAudioRTPSource.hh"
"/usr/include/liveMedia/TheoraVideoRTPSink.hh"
"/usr/include/liveMedia/Media.hh"
"/usr/include/liveMedia/RTSPCommon.hh"
"/usr/include/liveMedia/Base64.hh"
"/usr/include/liveMedia/MPEG1or2DemuxedServerMediaSubsession.hh"
"/usr/include/liveMedia/AudioRTPSink.hh"
"/usr/include/liveMedia/H264VideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/DVVideoFileServerMediaSubsession.hh"
"/usr/include/liveMedia/MP3FileSource.hh"
"/usr/include/liveMedia/FileServerMediaSubsession.hh"
"/usr/include/liveMedia/InputFile.hh"
"/usr/include/BasicUsageEnvironment/BasicUsageEnvironment0.hh"
"/usr/include/BasicUsageEnvironment/BasicUsageEnvironment.hh"
"/usr/include/BasicUsageEnvironment/HandlerSet.hh"
"/usr/include/BasicUsageEnvironment/DelayQueue.hh"
"/usr/include/BasicUsageEnvironment/BasicHashTable.hh"
"/usr/include/BasicUsageEnvironment/BasicUsageEnvironment_version.hh"
"/usr/include/UsageEnvironment/HashTable.hh"
"/usr/include/UsageEnvironment/UsageEnvironment_version.hh"
"/usr/include/UsageEnvironment/UsageEnvironment.hh"
"/usr/include/UsageEnvironment/strDup.hh"
"/usr/include/UsageEnvironment/Boolean.hh"

